# Generated by Django 3.1.3 on 2020-11-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.CharField(default='hello_world', max_length=1024, unique=True),
            preserve_default=False,
        ),
    ]
