# Generated by Django 3.1.3 on 2020-11-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='article',
            name='subtitle',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
