# Generated by Django 3.1.3 on 2020-11-24 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='public.service'),
        ),
    ]
