# Generated by Django 3.1.3 on 2020-11-24 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20201124_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='parent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='public.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='url',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
