# Generated by Django 3.1.3 on 2020-11-24 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_auto_20201124_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='public.service'),
        ),
    ]
