# Generated by Django 3.1.3 on 2020-11-24 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_auto_20201124_0135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
